export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_VERIFY_REQUEST = 'USER_VERIFY_REQUEST'
export const USER_VERIFY_SUCCESS = 'USER_VERIFY_SUCCESS'
export const USER_VERIFY_FAIL = 'USER_VERIFY_FAIL'

export const PASSWORD_FORGET_REQUEST = 'PASSWORD_FORGET_REQUEST'
export const PASSWORD_FORGET_SUCCESS = 'PASSWORD_FORGET_SUCCESS'
export const PASSWORD_FORGET_FAIL = 'PASSWORD_FORGET_FAIL'

export const TOKEN_VERIFY_REQUEST = 'TOKEN_VERIFY_REQUEST'
export const TOKEN_VERIFY_SUCCESS = 'TOKEN_VERIFY_SUCCESS'
export const TOKEN_VERIFY_FAIL = 'TOKEN_VERIFY_FAIL'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'
