export const POST_LIST_REQUEST = 'POST_LIST_REQUEST'
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const POST_LIST_FAIL = 'POST_LIST_FAIL'

export const POST_LIKE_REQUEST = 'POST_LIKE_REQUEST'
export const POST_LIKE_SUCCESS = 'POST_LIKE_SUCCESS'
export const POST_LIKE_FAIL = 'POST_LIKE_FAIL'
export const POST_LIKE_RESET = 'POST_LIKE_RESET'

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST'
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS'
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL'

export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST'
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS'
export const POST_COMMENT_FAIL = 'POST_COMMENT_FAIL'

export const USER_POST_LIST_REQUEST = 'USER_POST_LIST_REQUEST'
export const USER_POST_LIST_SUCCESS = 'USER_POST_LIST_SUCCESS'
export const USER_POST_LIST_FAIL = 'USER_POST_LIST_FAIL'

export const POST_BY_ID_REQUEST = 'POST_BY_ID_REQUEST'
export const POST_BY_ID_SUCCESS = 'POST_BY_ID_SUCCESS'
export const POST_BY_ID_FAIL = 'POST_BY_ID_FAIL'
